//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MasterSlaverSensor.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDR_MAINFRAME                   128
#define IDD_MASTERSLAVERSENSOR_DIALOG   130
#define IDC_EDIT_IP                     1000
#define IDC_STATIC_IP                   1001
#define IDC_STATIC_PORT                 1002
#define IDC_EDIT_PORT                   1003
#define IDC_STATIC_USER                 1004
#define IDC_EDIT_USER                   1005
#define IDC_STATIC_PWD                  1006
#define IDC_EDIT_PWD                    1007
#define IDC_BUTTON_LOGIN                1008
#define IDC_BUTTON_LOGOUT               1009
#define IDC_SCREEN_WINDOW               1012
#define IDC_BUTTON_PLAY                 1013
#define IDC_BUTTON_STOPPLAY             1014
#define IDC_COMBO_CHN                   1015
#define IDC_STATIC_CHANNEL              1016
#define IDC_STATI_SCREEN                1017
#define IDC_STATIC_CHANNEL2             1018
#define IDC_COMBO_SCREEN                1019
#define OPEN_GROUP                      1020
#define IDC_BUTTON_OPEN                 1020
#define IDC_BUTTON1                     1021
#define IDC_BUTTON_ADD_REMOTE           1021
#define IDC_EDIT1_REMOTE_IP             1022
#define IDC_EDIT_REMOTE_PORT            1023
#define IDC_PTZ_UP                      1024
#define IDC_PTZ_DOWN                    1025
#define IDC_EDIT_REMOTE_PASSWORD        1026
#define IDC_STATI                       1027
#define IDC_EDIT_REMOTE_USER            1028
#define IDC_BUTTON_BOND                 1029
#define IDC_BUTTON_LOGINREMOTE          1030
#define IDC_DOME_WINDOW                 1031
#define IDC_STATIC_CALIBRATION          1032
#define IDC_BUTTON_REMOTESTOP           1033
#define IDC_BUTTON_REMOTEPLAY           1034
#define IDC_BUTTON_REMOTELOGOUT         1035
#define IDC_PTZ_LEFTUP                  1036
#define IDC_EDIT_left1                  1037
#define IDC_PTZ_RIGHTUP                 1037
#define IDC_EDIT_right1                 1038
#define IDC_PTZ_LEFTDOWN                1038
#define IDC_EDIT_bottom1                1039
#define IDC_PTZ_RIGHTDOWN               1039
#define IDC_EDIT_left2                  1040
#define IDC_PTZ_LEFT                    1040
#define IDC_EDIT_top2                   1041
#define IDC_PTZ_RIGHT                   1041
#define IDC_EDIT_right2                 1042
#define IDC_ZOOM_WIDE                   1042
#define IDC_EDIT_top1                   1043
#define IDC_ZOOM_TELE                   1043
#define IDC_EDIT_bottom2                1044
#define IDC_COMBO_PTZDATA               1044
#define IDC_EDIT_top3                   1045
#define IDC_EDIT_right3                 1046
#define IDC_EDIT_bottom3                1047
#define IDC_EDIT1_left3                 1048
#define IDC_COMBO_CALIBRATE_SELECT      1049
#define IDC_COMBO_CALIBRATE_SELECT2     1050
#define IDC_EDIT3                       1051
#define IDC_EDIT4                       1052
#define IDC_EDIT5                       1053
#define IDC_EDIT6                       1054
#define IDC_EDIT7                       1055
#define IDC_EDIT8                       1056
#define IDC_EDIT9                       1057
#define IDC_EDIT10                      1058
#define IDC_EDIT11                      1059
#define IDC_EDIT12                      1060
#define IDC_EDIT13                      1061
#define IDC_EDIT14                      1062
#define IDC_EDIT15                      1063
#define IDC_EDIT16                      1064
#define IDC_EDIT17                      1065
#define IDC_EDIT18                      1066
#define IDC_EDIT19                      1067
#define IDC_EDIT20                      1068
#define IDC_EDIT21                      1069
#define IDC_EDIT22                      1070
#define IDC_EDIT23                      1071
#define IDC_EDIT24                      1072
#define IDC_EDIT25                      1073
#define IDC_EDIT26                      1074
#define IDC_EDIT27                      1075
#define IDC_EDIT28                      1076
#define IDC_EDIT29                      1077
#define IDC_EDIT30                      1078
#define IDC_EDIT31                      1079
#define IDC_EDIT32                      1080
#define IDC_EDIT33                      1081
#define IDC_EDIT34                      1082
#define IDC_BUTTON3                     1083
#define IDC_BUTTON_CALIBRATE_EACHSENSOR 1083
#define IDC_COMBO_GROUP_SELECT          1084
#define IDC_EDIT35                      1084
#define IDC_BUTTON_GETALLCALIBRATE      1085
#define IDC_BUTTON_CALIBRATE_EACHSENSOR2 1085
#define IDC_BUTTON_STARTCALIBRATE       1085
#define IDC_BUTTON_ADDOTHER             1086
#define IDC_BUTTON_DONE                 1087
#define IDC_BUTTON_FOUR                 1088
#define IDC_EDIT36                      1088
#define IDC_BUTTON_EIGHT                1089
#define IDC_EDIT37                      1089
#define IDC_BUTTON_FINISH               1090
#define IDC_BUTTON_new                  1091
#define IDC_STATIC_AUTOTRACK            1092
#define IDC_BUTTON_AUTOTRACK            1093
#define IDC_BUTTON_NOAUTOTRACK          1094
#define IDC_EDIT38                      1095
#define IDC_GET_SLAVEPOSITON1           1096
#define IDC_GET_SLAVEPOSITON2           1097
#define IDC_GET_SLAVEPOSITON3           1098
#define IDC_BUTTON6                     1099
#define IDC_GET_SLAVEPOSITON4           1099
#define IDC_DVRIPADDRESS                1100
#define IDC_PTZIPADDRESS                1101

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        131
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1101
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
